stages:
  - build
  - deploy

job 0:
  stage: .pre
  script: apachectl restart

job 1:
  stage: build
  script: git pull origin master

job 2:
  stage: deploy
  script: make deploy

job 3:
  stage: .post
  script: apachectl restart