<?php

namespace common\models;

use common\components\services\MySoliqUz;
use Yii;

/**
 * This is the model class for table "classifications".
 *
 * @property int $id
 * @property string|null $tin
 * @property string|null $groupCode
 * @property string|null $classCode
 * @property string|null $className
 * @property string|null $productCode
 * @property string|null $productName
 * @property int|null $enabled
 */
class Classifications extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'classifications';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['enabled'], 'default', 'value' => null],
            [['enabled'], 'integer'],
            [['tin'], 'string', 'max' => 9],
            [['groupCode', 'classCode'], 'string', 'max' => 50],
            [['className', 'productCode', 'productName'], 'string', 'max' => 500],
        ];
    }

    public function beforeDelete()
    {
        $data = [
           'tin'=>$this->tin,
           'class_code'=>$this->classCode
        ];
        MySoliqUz::deleteProductsClassifications($data);
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tin' => 'Tin',
            'groupCode' => 'Group Code',
            'classCode' => 'Class Code',
            'className' => 'Class Name',
            'productCode' => 'Product Code',
            'productName' => 'Product Name',
            'enabled' => 'Enabled',
        ];
    }
}
